version: '3.2'
services:
  db:
    container_name: 'database'
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - ayur_auth

  auth: # auth service container
    container_name: 'auth'
    build:
      dockerfile: Dockerfile
    env_file:
      - "./.env"
    restart: always
    networks:
      - ayur
      - ayur_auth


volumes:
  db:

networks:
  ayur:  # network to connect all ayur services
    driver: bridge
  ayur_auth:
    driver: bridge
  ayur_user:
    driver: bridge
  ayur_hospital_staff:
    driver: bridge
  ayur_checkups:
    driver: bridge