version: '3.8'
services:
  checkup_db:
    container_name: 'checkup_db'
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - checkup_db:/var/lib/postgresql/data
    ports:
      - "8989:5432"
    restart: always
    networks:
      - ayur_checkup

  hospital:
    container_name: 'checkup'
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    networks:
      - ayur_checkup
#      - ayur
    depends_on:
      - checkup_db

volumes:
  checkup_db:

networks:
  ayur_checkup:
    driver: 'bridge'
#  ayur:
#    external: true
