version: '3.8'
services:
  hospital_db:
    container_name: 'hospital_db'
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - hospital_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - ayur_hospital

  hospital:
    container_name: 'hospital'
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    networks:
      - ayur_hospital
    depends_on:
      - hospital_db

volumes:
  hospital_db:

networks:
  ayur_hospital:
    driver: 'bridge'
